title: Dr Who Episodes Data
description: A complete set of files listing all doctor who episodes, titles and other interesting data. 

publisher_text: David Tarrant
publisher_url: davetaz@gmail.com

license_text: CC0 - Public Domain
license_url: http://creativecommons.org/publicdomain/zero/1.0/

frequency: Yearly

certificate_embed:
